name: tutorpus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9  # SVG 파일 사용을 위한 패키지 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts: 
        - asset: fonts/PretendardVariable.ttf 
    - family: JeonjuCraft
      fonts: 
        - asset: fonts/JeonjuCraft_Go_Regular.ttf
